In [1]:
import numpy as np
import pandas as pd

In [2]:
movies =pd.read_csv("movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [3]:
#remove nan values

In [4]:
movies.dropna(inplace= True)

In [5]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,Kasoor,tt0272688,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kasoor,Kasoor,Kasoor,0,2001,151,Drama|Mystery|Thriller,6.0,801,Shekar Saxena is arrested and charged with the...,Shekhar appoints Simran a lawyer with an impe...,A dangerous passion...,Divya Dutta|Sucheta Paushe|Lisa Ray|Apoorva Ag...,2 nominations,2 February 2001 (India)
1601,Maya (2001 film),tt0299027,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Maya_(2001_film),Maya,Maya,0,2001,105,Drama,7.0,277,For 12 year-old Maya life is very simple in h...,MAYA is a coming of age story set against an '...,A child's innocence shattered by unreal tradit...,Anant Nag|Mita Vasisht|Nitya Shetty|Nikhil Yad...,2 wins & 4 nominations,16 January 2002 (Belgium)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)
1621,Tum Bin,tt0290326,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tum_Bin,Tum Bin...: Love Will Find a Way,Tum Bin...: Love Will Find a Way,0,2001,158,Drama|Romance,7.5,2879,Shekar and Amar meet at a party where Amar ask...,Shekhar accidentally kills his associate Amar ...,Love will find a way,Priyanshu Chatterjee|Himanshu Malik|Sandali Si...,6 nominations,13 July 2001 (India)
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)

In [6]:
ipl= pd.read_csv("ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [7]:
#changing datatype

In [8]:
ipl["ID"].astype("int32")

0      1312200
1      1312199
2      1312198
3      1312197
4      1304116
        ...
945     335986
946     335985
947     335984
948     335983
949     335982
Name: ID, Length: 950, dtype: int32

In [9]:
ipl["ID"]=ipl["ID"].astype("int32")

In [10]:
ipl.info() #.info give information about columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB

In [11]:
ipl["Season"].astype("category")

0         2022
1         2022
2         2022
3         2022
4         2022
        ...
945    2007/08
946    2007/08
947    2007/08
948    2007/08
949    2007/08
Name: Season, Length: 950, dtype: category
Categories (15, object): ['2007/08', '2009', '2009/10', '2011', ..., '2019', '2020/21', '2021', '2022']

In [12]:
ipl["Season"]=ipl["Season"].astype("category")

In [13]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(1), float64(1), int32(1), object(17)
memory usage: 139.0+ KB

In [14]:
mark= {
    "marks": 52,
    "english":54,
    "hindi": 55,
    "science": 60
}

In [15]:
m= pd.Series(mark)

In [16]:
m

marks      52
english    54
hindi      55
science    60
dtype: int64

In [17]:
m.sort_index(ascending= False)

science    60
marks      52
hindi      55
english    54
dtype: int64

In [18]:
m.reset_index()

     index   0
0    marks  52
1  english  54
2    hindi  55
3  science  60

In [19]:
movies.sort_index()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,Kasoor,tt0272688,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kasoor,Kasoor,Kasoor,0,2001,151,Drama|Mystery|Thriller,6.0,801,Shekar Saxena is arrested and charged with the...,Shekhar appoints Simran a lawyer with an impe...,A dangerous passion...,Divya Dutta|Sucheta Paushe|Lisa Ray|Apoorva Ag...,2 nominations,2 February 2001 (India)
1601,Maya (2001 film),tt0299027,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Maya_(2001_film),Maya,Maya,0,2001,105,Drama,7.0,277,For 12 year-old Maya life is very simple in h...,MAYA is a coming of age story set against an '...,A child's innocence shattered by unreal tradit...,Anant Nag|Mita Vasisht|Nitya Shetty|Nikhil Yad...,2 wins & 4 nominations,16 January 2002 (Belgium)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)
1621,Tum Bin,tt0290326,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tum_Bin,Tum Bin...: Love Will Find a Way,Tum Bin...: Love Will Find a Way,0,2001,158,Drama|Romance,7.5,2879,Shekar and Amar meet at a party where Amar ask...,Shekhar accidentally kills his associate Amar ...,Love will find a way,Priyanshu Chatterjee|Himanshu Malik|Sandali Si...,6 nominations,13 July 2001 (India)
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)

In [20]:
movies.rename(columns={"imdb_id":"imdb","poster_path":"link"},inplace= True)

In [21]:
movies

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,Kasoor,tt0272688,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kasoor,Kasoor,Kasoor,0,2001,151,Drama|Mystery|Thriller,6.0,801,Shekar Saxena is arrested and charged with the...,Shekhar appoints Simran a lawyer with an impe...,A dangerous passion...,Divya Dutta|Sucheta Paushe|Lisa Ray|Apoorva Ag...,2 nominations,2 February 2001 (India)
1601,Maya (2001 film),tt0299027,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Maya_(2001_film),Maya,Maya,0,2001,105,Drama,7.0,277,For 12 year-old Maya life is very simple in h...,MAYA is a coming of age story set against an '...,A child's innocence shattered by unreal tradit...,Anant Nag|Mita Vasisht|Nitya Shetty|Nikhil Yad...,2 wins & 4 nominations,16 January 2002 (Belgium)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)
1621,Tum Bin,tt0290326,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tum_Bin,Tum Bin...: Love Will Find a Way,Tum Bin...: Love Will Find a Way,0,2001,158,Drama|Romance,7.5,2879,Shekar and Amar meet at a party where Amar ask...,Shekhar accidentally kills his associate Amar ...,Love will find a way,Priyanshu Chatterjee|Himanshu Malik|Sandali Si...,6 nominations,13 July 2001 (India)
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)

In [22]:
y= pd.Series([1,2,1,2,5,6,1,7,1,2,8,3,1,2,5,6,np.nan])

In [23]:
y

0     1.0
1     2.0
2     1.0
3     2.0
4     5.0
5     6.0
6     1.0
7     7.0
8     1.0
9     2.0
10    8.0
11    3.0
12    1.0
13    2.0
14    5.0
15    6.0
16    NaN
dtype: float64

In [24]:
y.unique() # unique is used to show values that repeats

array([ 1.,  2.,  5.,  6.,  7.,  8.,  3., nan])

In [25]:
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [26]:
ipl["City"].unique()

array(['Ahmedabad', 'Kolkata', 'Mumbai', 'Navi Mumbai', 'Pune', 'Dubai',
       'Sharjah', 'Abu Dhabi', 'Delhi', 'Chennai', nan, 'Hyderabad',
       'Visakhapatnam', 'Chandigarh', 'Bengaluru', 'Jaipur', 'Indore',
       'Bangalore', 'Kanpur', 'Rajkot', 'Raipur', 'Ranchi', 'Cuttack',
       'Dharamsala', 'Kochi', 'Nagpur', 'Johannesburg', 'Centurion',
       'Durban', 'Bloemfontein', 'Port Elizabeth', 'Kimberley',
       'East London', 'Cape Town'], dtype=object)

In [27]:
# nunique fuction is used when we dont want to count nan values and shows how many values are unique

In [28]:
ipl["City"].nunique()

33

In [29]:
# is null is used to determine weather null values are present in object(columns) or not

In [30]:
ipl.isnull()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
946,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
947,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
948,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
949,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [31]:
ipl[ipl.isnull()] # WE store under same variable when we dont want bullian(true/false) values

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
movies.head()

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India)

In [33]:
g= movies.groupby("genres") # groupby is used to make group of columns

In [34]:
g

In [35]:
g.sum()

C:\Users\avnis\AppData\Local\Temp\ipykernel_24752\1197020669.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  g.sum()

                          is_adult  year_of_release  imdb_rating  imdb_votes
genres
Action                           0             2015          3.7         118
Action|Adventure|Comedy          0             2008          5.6        1896
Action|Adventure|Drama           0             8046         20.9        7548
Action|Adventure|Fantasy         0             2009          4.6        2540
Action|Adventure|Sci-Fi          0             2011          4.6       36221
...                            ...              ...          ...         ...
Drama|War                        0             2017          4.0       12911
Fantasy|Mystery|Romance          0             2012          3.9         783
Horror                           0             4029          7.5        3986
Mystery|Thriller                 0             4027         15.7       57131
Thriller                         0             2002          5.6        1099

[92 rows x 4 columns]

In [36]:
i=movies.groupby("imdb_rating")

In [37]:
i.sum()

C:\Users\avnis\AppData\Local\Temp\ipykernel_24752\1768248956.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  i.sum()

             is_adult  year_of_release  imdb_votes
imdb_rating
1.7                 0             2013        7470
1.8                 0             2014        7216
2.4                 0             2012        4716
2.5                 0             2010       10417
2.7                 0             2014         169
3.1                 0             4020        2742
3.2                 0             2014        2955
3.7                 0             6039        5786
3.8                 0             2014        2521
3.9                 0             2012         783
4.0                 0             8055       29722
4.1                 0             4014        4045
4.2                 0             8042        9219
4.3                 0             4017        2295
4.4                 0             4015        3963
4.6                 0            16068       54002
4.7                 0             4017        6679
4.8                 0             2006        1001
4.9                 0             8041       12709
5.0                 0             6026       13227
5.1                 0            14064       14934
5.2                 0            20082       39612
5.3                 0            22094       65738
5.4                 0            12051       56182
5.5                 0            12038       17128
5.6                 0            14064       17131
5.7                 0            10052       21325
5.8                 0             6041       17641
5.9                 0             6021        6585
6.0                 0            18062       86685
6.1                 0             6033        9377
6.2                 0            18064       27530
6.3                 0            12045       44237
6.4                 0             8030        7437
6.5                 0            20068       88243
6.6                 0            14033       54066
6.7                 0            20075      119149
6.8                 0            20097       90333
6.9                 0            14043       21350
7.0                 0            14078       93646
7.1                 0            28105      230851
7.2                 0            32143      197667
7.3                 0             6016       60235
7.4                 0            24093      186546
7.5                 0            12054       73566
7.6                 0            22121      132735
7.7                 0            14087      114403
7.8                 0            14073      190187
7.9                 0             6014       24311
8.0                 0            20106      339618
8.1                 0            16048      446203
8.2                 0            20111      519378
8.3                 0             4031       26954
8.4                 0             6032      590317
8.5                 0             2004       16761

In [38]:
movies.groupby("genres")["imdb_rating"].mean()

genres
Action                      3.700
Action|Adventure|Comedy     5.600
Action|Adventure|Drama      5.225
Action|Adventure|Fantasy    4.600
Action|Adventure|Sci-Fi     4.600
                            ...
Drama|War                   4.000
Fantasy|Mystery|Romance     3.900
Horror                      3.750
Mystery|Thriller            7.850
Thriller                    5.600
Name: imdb_rating, Length: 92, dtype: float64

In [39]:
len(movies.groupby("genres"))

92

In [40]:
movies.groupby("genres").nunique()

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
genres,,,,,,,,,,,,,,,,,
Action,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Action|Adventure|Comedy,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Action|Adventure|Drama,4,4,4,4,4,4,1,4,4,4,4,4,4,4,4,4,4
Action|Adventure|Fantasy,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Action|Adventure|Sci-Fi,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Drama|War,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Fantasy|Mystery|Romance,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Horror,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2
Mystery|Thriller,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2
Thriller,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [41]:
movies.groupby("genres").size()

genres
Action                      1
Action|Adventure|Comedy     1
Action|Adventure|Drama      4
Action|Adventure|Fantasy    1
Action|Adventure|Sci-Fi     1
                           ..
Drama|War                   1
Fantasy|Mystery|Romance     1
Horror                      2
Mystery|Thriller            2
Thriller                    1
Length: 92, dtype: int64

In [42]:
genres= movies.groupby("genres")
genres.nth(6)

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
genres,,,,,,,,,,,,,,,,,
Action|Crime|Drama,Game (2011 film),tt1772872,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Game_(2011_film),Game,Game,0,2011,135,5.1,1786,Four strangers (Neil Menon OP Ramsay Tisha K...,A wealthy man invites four people to his priva...,It's not Over till its Over,Abhishek Bachchan|Kangana Ranaut|Anupam Kher|B...,2 wins,1 April 2011 (India)
Action|Drama|Romance,Gadar: Ek Prem Katha,tt0284137,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gadar:_Ek_Prem_K...,Gadar: Ek Prem Katha,Gadar: Ek Prem Katha,0,2001,170,7.2,9372,Amongst the communal riots that erupt in the c...,Set during the Partition of India in 1947 a S...,A saga of love during the Indo-Pak partition.,Sunny Deol|Ameesha Patel|Amrish Puri|Lillete D...,7 wins & 33 nominations,15 June 2001 (India)
Action|Drama|Thriller,Aurangzeb (film),tt2804026,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aurangzeb_(film),Aurangzeb,Aurangzeb,0,2013,137,6.5,3674,"Gurgaon is the most modern boom-town of ""India...",Kingship knows no Kinship and there can be onl...,You are a king| or nothing.,Arjun Kapoor|Prithviraj Sukumaran|Jackie Shrof...,2 wins & 5 nominations,17 May 2013 (USA)
Action|Thriller,Holiday: A Soldier Is Never Off Duty,tt2556308,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Holiday_(2014_film),Holiday,Holiday,0,2014,160,7.2,23733,Virat (Akshay Kumar) is among a battalion of m...,A military officer uses his intellect and figh...,A Soldier is never off duty.,Akshay Kumar|Sonakshi Sinha|Freddy Daruwala|Su...,4 wins & 3 nominations,6 June 2014 (India)
Comedy|Drama,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots,3 Idiots,3 Idiots,0,2009,170,8.4,310481,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
Comedy|Drama|Romance,Dostana (2008 film),tt1185420,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dostana_(2008_film),Dostana,Dostana,0,2008,145,6.5,12910,After the passing of her parents Neha Melwani...,Two straight guys pretend to be gay in order t...,The party begins at a cinema near you.,Abhishek Bachchan|John Abraham|Priyanka Chopra...,3 wins & 10 nominations,14 November 2008 (India)
Comedy|Romance,Mumbai Matinee,tt0382188,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mumbai_Matinee,Mumbai Matinee,Mumbai Matinee,0,2003,125,5.2,228,Debu Chatterjee is in his 30s and is chided b...,Debu Chatterjee is in his 30s and is chided b...,The magical love story of a 32 year old virgin,Rahul Bose|Perizaad Zorabian|Vijay Raaz|Saurab...,1 nomination,26 September 2003 (India)
Drama,Listen... Amaya,tt2224313,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Listen..._Amaya,Listen... Amaya,Listen... Amaya,0,2013,108,6.8,553,(Hindi with English subtitles) In this poignan...,(Hindi with English subtitles) In this poignan...,You don't always have to be right| you have to...,Farooq Shaikh|Deepti Naval|Swara Bhaskar|Amala...,1 win,1 February 2013 (India)
Drama|Musical|Romance,Sur – The Melody of Life,tt0332766,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sur:_The_Melody_...,Sur,Sur: The Melody of Life,0,2002,\N,6.4,413,Tina Marie D'Silva lives a middle-class lifest...,Tina Marie D'Silva lives a middle-class lifest...,The Melody of Life,Lucky Ali|Simone Singh|Achint Kaur|Ehsan Khan|...,3 nominations,13 September 2002 (India)
Drama|Romance,U Me Aur Hum,tt1039995,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/U_Me_Aur_Hum,U Me Aur Hum,U Me Aur Hum,0,2008,156,5.9,2325,The first time Ajay saw Pia she served him dr...,Ajay's life turns upside down when he learns t...,Sometimes the greatest journey is the distance...,Ajay Devgn|Kajol|Sumeet Raghvan|Divya Dutta|Is...,1 win & 1 nomination,11 April 2008 (USA)

In [43]:
movies.groupby("genres").value_counts()

genres                   title_x                        imdb       link                                                                                                                              wiki_link                                                    title_y                        original_title                 is_adult  year_of_release  runtime  imdb_rating  imdb_votes  story                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           summary                                                                                                                                                                                                             tagline                                             actors                                                                                                                                                                                                                wins_nominations          release_date
Action                   Ranbanka                       tt5151622  https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Ranbanka.jpg/220px-Ranbanka.jpg                                              https://en.wikipedia.org/wiki/Ranbanka                       Ranbanka                       Ranbanka                       0         2015             98       3.7          118         Rahul  an engineer  tries his best to protect his wife from a goon feared by all. The goon wants to marry Rahul's wife at any cost  and this doesn't bother him whether she is already married or she has a son. In the process  Rahul tries to take help from the law  but all efforts go awry  and the tables turn on him. When finally everything goes against him and his wife  he turns into an angry man  who is on a rampage to protect his wife by all means  even if it means killing the goon  and giving him the worst death he can ever wish for.                                                                                                                                                                                                   A non-violent engineer resorts to violence after his attempts to save his family from a local goon result in his son's murder.                                                                                      A Film By Aryeman                                   Manish Paul|Ravi Kishan|Pooja Thakur|Rudra Kaushik|Avya Agarwal|Avinash Dwivedi|                                                                                                                                      1 win                     6 November 2015 (India)    1
Action|Adventure|Comedy  Heroes (2008 film)             tt1114725  https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Heroes_Hindi_Film.jpg/220px-Heroes_Hindi_Film.jpg                            https://en.wikipedia.org/wiki/Heroes_(2008_film)             Heroes                         Heroes                         0         2008             139      5.6          1896        Havaldar Balkar Singh  Captain Dhananjay Shergill and Lieutenant Sahil Naqvi are amongst numerous fatalities on India's side in the 1999 Kargil war against Pakistan. All 3 men had written their last letters to Kuljeet Kaur  Squadron Leader Vikram Singh  and Dr. Naqvi respectively. These letters were located 3 years later by IBN Reporter  Avinash Sarin  who entrusts them to two Indore-based slackers  Ali Shah and Sameer Suri  and asks them to deliver them to Chandigarh  Manali  and Leh respectively. Ali and Sameer set out to film this journey in order to get a graduation degree so that they can re-locate to America as well as televise it widely in order to convince the youth not to join any of India's armed forces.             Two boys travel a thousand miles to deliver three letters as a part of their film school assignment. However  little do they know that the journey they have embarked upon will give a new meaning to their life.   Heroes are not born| but created by circumstances!  Sohail Khan|Vatsal Sheth|Amrita Arora|Riya Sen|Mohnish Bahl|Preity Zinta|Salman Khan|Dwij Yadav|Bobby Deol|Sunny Deol|Hrishitaa Bhatt|Dino Morea|Prateeksha Lonkar|Mithun Chakraborty|                                1 nomination              24 October 2008 (India)    1
Action|Adventure|Drama   Yeh Hai India                  tt5525846  https://upload.wikimedia.org/wikipedia/en/thumb/d/db/Yeh_Hai_India_Official_Poster.jpg/220px-Yeh_Hai_India_Official_Poster.jpg    https://en.wikipedia.org/wiki/Yeh_Hai_India                  Yeh Hai India                  Yeh Hai India                  0         2017             128      5.7          169         Yeh Hai India  follows the story of a 25 years old NRI  who is born and brought up in U.K and shares the same stereotype views of India  which is known for its vast population  pollution and poverty. However protagonist finds new development in media or probably an 'other side of same coin' of India  which is also known for successful mars mission in first attempt  a nation which proudly holds title 'God of Cricket' for Sachin Tendulkar  who is again an Indian and a nation which is known for its holy generosity with icons like Mother Teresa".                                                                                                                                                                                            Yeh Hai India  follows the story of a 25 years old NRI  who is born and brought up in UK. He shares the same stereotypical views about India that most NRIs have and how his perception changes.                    A Film for Every Indian                             Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|                                                                                                                                                                      2 wins & 1 nomination     24 May 2019 (India)        1
                         The Hero: Love Story of a Spy  tt0347167  https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Herolovestoryofaspy.jpg/220px-Herolovestoryofaspy.jpg                        https://en.wikipedia.org/wiki/The_Hero:_Love_Story_of_a_Spy  The Hero: Love Story of a Spy  The Hero: Love Story of a Spy  0         2003             160      5.2          1901        Arun Khanna is a spy for the Indian government whose aid is enlisted to stop ISI Chief Ishak Khan. Khan is trying to build a nuclear bomb with which he can liberate Kashmir from the Indians. A battle of wits ensues. When Khan detonates a bomb at Khanna's engagement party to a fellow spy  Khanna's resolve is only strengthened. Now not only does he have to fight Khan  but he also has to track down his missing fiancee.                                                                                                                                                                                                                                                                                                                             Arun is an Indian undercover agent enlisted to stop ISI chief Ishaq Khan. The village girl Reshma helps him but endangers her own life.                                                                             Love story of a spy                                 Sunny Deol|Preity Zinta|Priyanka Chopra|Amrish Puri|Kabir Bedi|Parvin Dabas|Rajpal Yadav|Yvonne Maverick|                                                                                                             6 nominations             10 April 2003 (India)      1
                         Raavan                         tt1334470  https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/Raavanposter2.jpg/220px-Raavanposter2.jpg                                    https://en.wikipedia.org/wiki/Raavan                         Raavan                         Raavan                         0         2010             130      5.4          3897        Ragini re-locates to distant Lal Matti along with her Superintendent of Police husband  Dev Pratap Sharma  in order to enable him to apprehend a bandit  Beera Munda. Shortly thereafter her life will be turned upside down when she will be abducted by Beera and held captive. It is during this captivity she will not only find out that her fate will be decided within 14 hours  but also the real reason behind her abduction.                                                                                                                                                                                                                                                                                                                          A bandit leader kidnaps the wife of the policeman who killed his sister  but later falls in love with her.                                                                                                          Not just a story| a world.                          Abhishek Bachchan|Aishwarya Rai Bachchan|Govinda|Vikram|Ajay Gehi|Ravi Kishan|Priyamani|Nikhil Dwivedi|                                                                                                               1 win & 2 nominations     18 June 2010 (USA)         1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
Horror                   Ragini MMS 2                   tt2609218  https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Ragini_MMS_2_Poster.jpg/220px-Ragini_MMS_2_Poster.jpg                        https://en.wikipedia.org/wiki/Ragini_MMS_2                   Ragini MMS 2                   Ragini MMS 2                   0         2014             119      3.8          2521        The film revolves around a haunted house where an infamous MMS is shot on a girl called Ragini which goes viral. the girl kills her boyfriend and claims that a witch had killed him. She ends up in a mental asylum. Later a film is planned based on the story  the same haunted house being the location of the film. Sunny Leone is cast to play the role or Ragini. Sunny goes to meet Ragini to understand her role better. But the meeting turns out violent. On one hand Ragini's doctor tries to solve the mystery and on the other hand shooting starts with unexplainable events. Junior artists get killed one by one. At last the scriptwriter Satya and Dr. Dutta have to fight the ghost to stay alive and save Sunny.                           A sleazy film director's decision to shoot his latest erotic horror movie in a notorious haunted house angers the vengeful spirit of its past inhabitant.                                                           Do Mein Zyada Maza Hai.                             Sunny Leone|Saahil Prem|Parvin Dabas|Sandhya Mridul|Divya Dutta|Soniya Mehra|Anita Hassanandani Reddy|Karan Veer Mehra|Karan Taluja|Kainaz Motivala|Rani Vashisht|Sagar Talashikar|Geetanjali Kulkarni|Jasvir Saini|  4 wins & 2 nominations    21 March 2014 (India)      1
                         Alone (2015 Hindi film)        tt4271730  https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Alone_-_2015_Hindi_film_poster.jpg/220px-Alone_-_2015_Hindi_film_poster.jpg  https://en.wikipedia.org/wiki/Alone_(2015_Hindi_film)        Alone                          Alone                          0         2015             133      3.7          1465        Conjoined at birth  Anjana and Sanjana were twin sisters who lived by one promise made to each other - 'We will always be together. We will never separate'. Mysterious circumstances lead to the death of one while the other survived. Years later  the ghost of the dead comes back to haunt the surviving sister. Why was the promise broken?                                                                                                                                                                                                                                                                                                                                                                                                               A supernatural mystery about a young woman whose dead sister relentlessly haunts her.                                                                                                                               She was never alone                                 Bipasha Basu|Karan Singh Grover|Sulabha Arya|Zakir Hussain|Neena Gupta|Nilima Priya|Sanjay Sharma|                                                                                                                    1 win                     16 January 2015 (India)    1
Mystery|Thriller         Rahasya                        tt3337550  https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Rahasya_poster.jpg/220px-Rahasya_poster.jpg                                  https://en.wikipedia.org/wiki/Rahasya                        Rahasya                        Rahasya                        0         2015             123      7.6          3950        A Doctor stands accused of killing his own eighteen-year old daughter. While this aggrieved father protests his innocence  all evidence points towards him irrefutably. While his own wife suspects him too  the C.B.I. sleuth on the case concludes that the doctor could not have killed his own daughter. So then  who did it? And why? As the C.B.I sleuth seeks these answers  he uncovers a vicious web of adultery and hidden family secrets...                                                                                                                                                                                                                                                                                                          A Doctor stands accused of killing his own eighteen-year old daughter. While this aggrieved father protests his innocence  all evidence points towards him irrefutably. While his own wife ...                      Can a father kill his own daughter?                 Kay Kay Menon|Ashish Vidyarthi|Tisca Chopra|Mita Vasisht|Ashwini Kalsekar|Kakar Vinit|Jitendra Barsiwal|Farida Dadi|Ramesh Deo|Usha Jadhav|Bikramjeet Kanwarpal|Murari Kumar|Aarush Maurya|Nimai Bali|                1 win                     30 January 2015 (India)    1
                         Kahaani                        tt1821480  https://upload.wikimedia.org/wikipedia/en/thumb/8/85/KahaaniPoster.jpg/220px-KahaaniPoster.jpg                                    https://en.wikipedia.org/wiki/Kahaani                        Kahaani                        Kahaani                        0         2012             122      8.1          53181       Kolkata is abuzz with the preparations for the annual Durga Puja festival  as seven months pregnant Vidya Bagchi steps off the airplane from London. Her first stop is the local police station to file a missing person report. Weeks ago  her husband Arnab arrived in India for a job assignment. The first two weeks  they talked daily on the phone  and then without explanation  his calls stopped. Everywhere Vidya turns  no one can remember Arnab. There is no trace of him at the guest house or his workplace. But Vidya will not give up her search. Somewhere in Kolkata she will discover the dangerous truth.                                                                                                                                  A pregnant woman's search for her missing husband takes her from London to Kolkata  but everyone she questions denies having ever met him.                                                                          A mother of a story                                 Vidya Balan|Parambrata Chattopadhyay|Indraneil Sengupta|Nawazuddin Siddiqui|Dhritiman Chatterjee|Saswata Chatterjee|Darshan Jariwala|                                                                                 19 wins & 18 nominations  9 March 2012 (India)       1
Thriller                 Road (film)                    tt0315632  https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Road_poster.jpg/220px-Road_poster.jpg                                        https://en.wikipedia.org/wiki/Road_(2002_film)               Road                           Road                           0         2002             134      5.6          1099        Arvind Chauhan (Vivek Oberooi) and Lakhsmi (Antara Mali) are in love with each other. Lakhsmi's dad  a senior police inspector  hates Arvind  and so Arvind and Lakshmi decide to elope and get married. On the way they allow Babu  a stranded motorist  to ride with them. After a short while  Babu irritates both of them and they ask him to leave  instead Babu draws a gun  and asks Arvind to get out  and drives away with Lakhsmi. Arvind  with the help of a truck-driver  Inderpal (Makrand Deshpande)  catches up with Babu  and Babu runs away. Arvind files a police report  and they proceed on their way. That's when they find Babu in the back of their vehicle  angry and resentful  and this time determined to have his way with them...  A couple decide to pick up a hitchhiker  but he ends up being a psychotic stalker who puts in them in danger.                                                                                                       Drive carefully                                     Manoj Bajpayee|Vivek Oberoi|Antara Mali|Sayaji Shinde|Makrand Deshpande|Rajpal Yadav|Vijay Raaz|Ganesh Yadav|Raj Zutshi|Rajnish Thakur|Mithilesh Chaturvedi|Vidya Phadnis|Ganesh Acharya|                             1 win & 2 nominations     27 September 2002 (USA)    1
Length: 298, dtype: int64

In [44]:
genres.get_group("Action")

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
452,Ranbanka,tt5151622,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ranbanka,Ranbanka,Ranbanka,0,2015,98,Action,3.7,118,Rahul an engineer tries his best to protect ...,A non-violent engineer resorts to violence aft...,A Film By Aryeman,Manish Paul|Ravi Kishan|Pooja Thakur|Rudra Kau...,1 win,6 November 2015 (India)

In [45]:
movies[movies['genres']=="Action"]

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
452,Ranbanka,tt5151622,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ranbanka,Ranbanka,Ranbanka,0,2015,98,Action,3.7,118,Rahul an engineer tries his best to protect ...,A non-violent engineer resorts to violence aft...,A Film By Aryeman,Manish Paul|Ravi Kishan|Pooja Thakur|Rudra Kau...,1 win,6 November 2015 (India)

In [46]:
movies.head()

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA)
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
96,Raid (2018 film),tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...,2 wins & 3 nominations,16 March 2018 (India)

In [47]:
genres.groups

{'Action': [452], 'Action|Adventure|Comedy': [1029], 'Action|Adventure|Drama': [34, 355, 858, 1398], 'Action|Adventure|Fantasy': [965], 'Action|Adventure|Sci-Fi': [807], 'Action|Adventure|Thriller': [159, 962], 'Action|Biography|Crime': [105], 'Action|Biography|Drama': [354, 1581], 'Action|Comedy': [593, 629, 729, 734, 975], 'Action|Comedy|Crime': [775, 980], 'Action|Comedy|Drama': [1111, 1168, 1314, 1320], 'Action|Comedy|Fantasy': [160], 'Action|Comedy|Musical': [733], 'Action|Crime': [1124], 'Action|Crime|Drama': [96, 165, 251, 380, 391, 615, 814, 870, 891, 927, 969, 1058, 1167, 1242, 1259, 1293, 1318, 1366, 1426, 1491, 1495, 1579], 'Action|Crime|Horror': [1578], 'Action|Crime|Thriller': [575, 832, 886, 1162, 1164, 1317], 'Action|Drama': [112, 228, 458, 493, 1511, 1552], 'Action|Drama|History': [171], 'Action|Drama|Mystery': [979, 1224], 'Action|Drama|Romance': [628, 682, 873, 1361, 1394, 1480, 1569], 'Action|Drama|Sport': [307, 850], 'Action|Drama|Thriller': [106, 164, 278, 341, 433, 449, 600, 1079, 1332, 1607], 'Action|Drama|War': [716, 1039, 1325], 'Action|Sci-Fi': [1186], 'Action|Sci-Fi|Thriller': [857], 'Action|Thriller': [87, 99, 123, 182, 346, 365, 518, 561, 596, 652, 799, 915, 1575], 'Action|Thriller|War': [169], 'Adventure|Animation|Comedy': [1030], 'Adventure|Biography|Drama': [431], 'Adventure|Comedy|Drama': [528, 1184], 'Adventure|Drama|Musical': [1567, 1568], 'Adventure|Horror|Mystery': [1258], 'Adventure|Horror|Romance': [840], 'Biography|Crime|Drama': [638], 'Biography|Crime|Thriller': [229], 'Biography|Drama': [116, 254, 1083], 'Biography|Drama|History': [216, 224, 1275, 1370, 1623], 'Biography|Drama|Romance': [550, 1142], 'Biography|Drama|Sport': [332, 612], 'Biography|Drama|Thriller': [269], 'Comedy': [512, 750, 854, 1439], 'Comedy|Crime': [901, 970, 1191], 'Comedy|Crime|Drama': [862, 1225, 1489, 1493], 'Comedy|Drama': [185, 211, 405, 469, 586, 868, 912, 916, 971, 1195, 1348], 'Comedy|Drama|Family': [766, 1006, 1114, 1309], 'Comedy|Drama|Fantasy': [485, 714, 856], 'Comedy|Drama|Music': [978], 'Comedy|Drama|Musical': [1316, 1403, 1544], 'Comedy|Drama|Romance': [209, 275, 666, 689, 695, 747, 976, 1035, 1097, 1106, 1183, 1189, 1230, 1274, 1291, 1395, 1542, 1571], 'Comedy|Drama|Thriller': [1206], 'Comedy|Family': [879], 'Comedy|Family|Sci-Fi': [703], 'Comedy|Music': [1448], 'Comedy|Musical|Romance': [1141], 'Comedy|Mystery|Thriller': [1135], 'Comedy|Romance': [218, 459, 715, 818, 1063, 1251, 1464], 'Comedy|Romance|Sci-Fi': [911], 'Comedy|Thriller': [639], 'Crime|Drama': [37, 985, 1450, 1472, 1574], 'Crime|Drama|Mystery': [426, 727, 1099, 1312], 'Crime|Drama|Romance': [998], 'Crime|Drama|Thriller': [578, 930, 941], 'Crime|Mystery|Thriller': [1470], 'Crime|Short': [1425], 'Crime|Thriller': [560], 'Drama': [226, 252, 326, 418, 474, 562, 577, 634, 710, 829, 890, 1014, 1055, 1105, 1143, 1163, 1202, 1223, 1254, 1284, 1295, 1328, 1333, 1346, 1384, 1483, 1588, 1601], 'Drama|Family': [1127, 1308], 'Drama|Family|Musical': [1208, 1313], 'Drama|Family|Romance': [1414, 1494], 'Drama|Family|Sport': [1066], 'Drama|Fantasy|Romance': [1288, 1500], 'Drama|History': [256, 933], 'Drama|History|Musical': [1301], 'Drama|History|War': [1401, 1402], 'Drama|Horror': [1421], 'Drama|Horror|Musical': [1487], 'Drama|Horror|Mystery': [543, 765, 1280], 'Drama|Music': [11, 1016, 1285], 'Drama|Musical': [1336], 'Drama|Musical|Romance': [1120, 1176, 1269, 1412, 1413, 1490, 1561, 1565, 1573], 'Drama|Music|Musical': [591], 'Drama|Mystery|Thriller': [1600], 'Drama|Romance': [100, 162, 264, 265, 635, 663, 993, 1166, 1378, 1397, 1399, 1458, 1519, 1621], 'Drama|Romance|Thriller': [1138, 1216, 1323], 'Drama|Sport': [581], 'Drama|Thriller': [1147, 1321, 1442], 'Drama|War': [200], 'Fantasy|Mystery|Romance': [681], 'Horror': [370, 475], 'Mystery|Thriller': [376, 669], 'Thriller': [1551]}

In [48]:
genres.describe()

                         is_adult                                     \
                            count mean  std  min  25%  50%  75%  max
genres
Action                        1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Comedy       1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Drama        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Fantasy      1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Sci-Fi       1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
...                           ...  ...  ...  ...  ...  ...  ...  ...
Drama|War                     1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Fantasy|Mystery|Romance       1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Horror                        2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Mystery|Thriller              2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Thriller                      1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0

                         year_of_release          ... imdb_rating       \
                                   count    mean  ...         75%  max
genres                                            ...
Action                               1.0  2015.0  ...       3.700  3.7
Action|Adventure|Comedy              1.0  2008.0  ...       5.600  5.6
Action|Adventure|Drama               4.0  2011.5  ...       5.475  5.7
Action|Adventure|Fantasy             1.0  2009.0  ...       4.600  4.6
Action|Adventure|Sci-Fi              1.0  2011.0  ...       4.600  4.6
...                                  ...     ...  ...         ...  ...
Drama|War                            1.0  2017.0  ...       4.000  4.0
Fantasy|Mystery|Romance              1.0  2012.0  ...       3.900  3.9
Horror                               2.0  2014.5  ...       3.775  3.8
Mystery|Thriller                     2.0  2013.5  ...       7.975  8.1
Thriller                             1.0  2002.0  ...       5.600  5.6

                         imdb_votes                                            \
                              count     mean           std      min       25%
genres
Action                          1.0    118.0           NaN    118.0    118.00
Action|Adventure|Comedy         1.0   1896.0           NaN   1896.0   1896.00
Action|Adventure|Drama          4.0   1887.0   1536.820961    169.0   1228.00
Action|Adventure|Fantasy        1.0   2540.0           NaN   2540.0   2540.00
Action|Adventure|Sci-Fi         1.0  36221.0           NaN  36221.0  36221.00
...                             ...      ...           ...      ...       ...
Drama|War                       1.0  12911.0           NaN  12911.0  12911.00
Fantasy|Mystery|Romance         1.0    783.0           NaN    783.0    783.00
Horror                          2.0   1993.0    746.704761   1465.0   1729.00
Mystery|Thriller                2.0  28565.5  34811.573945   3950.0  16257.75
Thriller                        1.0   1099.0           NaN   1099.0   1099.00


                              50%       75%      max
genres
Action                      118.0    118.00    118.0
Action|Adventure|Comedy    1896.0   1896.00   1896.0
Action|Adventure|Drama     1741.0   2400.00   3897.0
Action|Adventure|Fantasy   2540.0   2540.00   2540.0
Action|Adventure|Sci-Fi   36221.0  36221.00  36221.0
...                           ...       ...      ...
Drama|War                 12911.0  12911.00  12911.0
Fantasy|Mystery|Romance     783.0    783.00    783.0
Horror                     1993.0   2257.00   2521.0
Mystery|Thriller          28565.5  40873.25  53181.0
Thriller                   1099.0   1099.00   1099.0

[92 rows x 32 columns]

In [49]:
genres.nunique()  # remove nan values

,title_x,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
genres,,,,,,,,,,,,,,,,,
Action,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Action|Adventure|Comedy,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Action|Adventure|Drama,4,4,4,4,4,4,1,4,4,4,4,4,4,4,4,4,4
Action|Adventure|Fantasy,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Action|Adventure|Sci-Fi,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Drama|War,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Fantasy|Mystery|Romance,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Horror,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2
Mystery|Thriller,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2
Thriller,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [50]:
#agg method

genres.agg(["mean","max","min"])

C:\Users\avnis\AppData\Local\Temp\ipykernel_24752\2186192605.py:3: FutureWarning: ['title_x', 'imdb', 'link', 'wiki_link', 'title_y', 'original_title', 'runtime', 'story', 'summary', 'tagline', 'actors', 'wins_nominations', 'release_date'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  genres.agg(["mean","max","min"])

                         is_adult         year_of_release              \
                             mean max min            mean   max   min
genres
Action                        0.0   0   0          2015.0  2015  2015
Action|Adventure|Comedy       0.0   0   0          2008.0  2008  2008
Action|Adventure|Drama        0.0   0   0          2011.5  2017  2003
Action|Adventure|Fantasy      0.0   0   0          2009.0  2009  2009
Action|Adventure|Sci-Fi       0.0   0   0          2011.0  2011  2011
...                           ...  ..  ..             ...   ...   ...
Drama|War                     0.0   0   0          2017.0  2017  2017
Fantasy|Mystery|Romance       0.0   0   0          2012.0  2012  2012
Horror                        0.0   0   0          2014.5  2015  2014
Mystery|Thriller              0.0   0   0          2013.5  2015  2012
Thriller                      0.0   0   0          2002.0  2002  2002

                         imdb_rating           imdb_votes
                                mean  max  min       mean    max    min
genres
Action                         3.700  3.7  3.7      118.0    118    118
Action|Adventure|Comedy        5.600  5.6  5.6     1896.0   1896   1896
Action|Adventure|Drama         5.225  5.7  4.6     1887.0   3897    169
Action|Adventure|Fantasy       4.600  4.6  4.6     2540.0   2540   2540
Action|Adventure|Sci-Fi        4.600  4.6  4.6    36221.0  36221  36221
...                              ...  ...  ...        ...    ...    ...
Drama|War                      4.000  4.0  4.0    12911.0  12911  12911
Fantasy|Mystery|Romance        3.900  3.9  3.9      783.0    783    783
Horror                         3.750  3.8  3.7     1993.0   2521   1465
Mystery|Thriller               7.850  8.1  7.6    28565.5  53181   3950
Thriller                       5.600  5.6  5.6     1099.0   1099   1099

[92 rows x 12 columns]

In [51]:
genres.agg({
    "imdb_votes": 'mean'
})

                          imdb_votes
genres
Action                         118.0
Action|Adventure|Comedy       1896.0
Action|Adventure|Drama        1887.0
Action|Adventure|Fantasy      2540.0
Action|Adventure|Sci-Fi      36221.0
...                              ...
Drama|War                    12911.0
Fantasy|Mystery|Romance        783.0
Horror                        1993.0
Mystery|Thriller             28565.5
Thriller                      1099.0

[92 rows x 1 columns]